export const PURCHASE_BURGER_START = 'order.PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'order.PURCHASE_BURGER_SUCCESS'
export const PURCHASE_BURGER_ERROR = 'order.PURCHASE_BURGER_ERROR'

export const PURCHASE_INIT = 'order.PURCHASE_INIT'

export const FETCH_ORDERS_START = 'order.FETCH_ORDERS_START'
export const FETCH_ORDERS_SUCCESS = 'order.FETCH_ORDERS_SUCCESS'
export const FETCH_ORDERS_ERROR = 'order.FETCH_ORDERS_ERROR'

export const REMOVE_ORDER = 'order.REMOVE_ORDER'
export const REMOVE_ORDER_SUCCESS = 'order.REMOVE_ORDER_SUCCESS'
export const REMOVE_ORDER_ERROR = 'order.REMOVE_ORDER_ERROR'