export const AUTH_USER = 'auth.AUTH_USER'
export const AUTH_START = 'auth.AUTH_START'
export const AUTH_SUCCES = 'auth.AUTH_SUCCES'
export const AUTH_FAIL = 'auth.AUTH_FAIL'

export const AUTH_LOGOUT = 'auth.AUTH_LOGOUT'
export const AUTH_INITIATE_LOGOUT = 'auth.AUTH_INITIATE_LOGOUT'
export const AUTH_CHECK_TIMEOUT = 'auth.AUTH_CHECK_TIMEOUT'
export const AUTH_CHECK_STATE = 'auth.AUTH_CHECK_STATE'
export const SET_AUTH_REDIRECT_PATH = 'auth.SET_AUTH_REDIRECT_PATH'